INSERT INTO concept (id, parent_id, name, description) VALUES (1, NULL, 'Software', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (2, 1, 'Algorithm', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (3, 1, 'Data Structures', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (4, 1, 'Concurrency', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (5, 1, 'Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (6, 1, 'Object Oriented Programming', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (7, 1, 'Functional Programming', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (8, 1, 'Operating System', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (9, 1, 'Network', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (10, 1, 'Security', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (11, 1, 'High Availability', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (12, 1, 'Scalability', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (13, 1, 'Database', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (14, 2, 'Sorting Algorithm', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (15, 2, 'Graph Algorithm', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (16, 2, 'Algorithmic Complexity', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (17, 3, 'Stack', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (18, 3, 'Queue', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (19, 3, 'Linked List', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (20, 3, 'Hash Table', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (21, 3, 'Binary Search Tree', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (22, 3, 'Red Black Tree', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (23, 3, 'B Tree', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (24, 3, 'Heap', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (25, 3, 'Binomial Heap', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (26, 3, 'Fibonacci Heap', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (27, 3, 'Graph', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (28, 3, 'Directed Graph', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (29, 3, 'Directed Acyclic Graph', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (30, 3, 'Adjacency List', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (31, 3, 'Adjacency Matrix', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (32, 4, 'Parallel Computing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (33, 4, 'Atomicity', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (34, 4, 'Atomic', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (35, 4, 'Multiversion Concurrency Control', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (36, 4, 'Optimistic Locking', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (37, 4, 'Pessimistic Locking', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (38, 4, 'Two Phase Locking', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (39, 4, 'Multithreaded', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (40, 4, 'Criticial Section', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (41, 4, 'Preemption', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (42, 4, 'Race Condition', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (43, 4, 'Deadlock', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (44, 4, 'Syncrhonization', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (45, 5, 'Object Oriented Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (46, 5, 'Behavioral Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (47, 5, 'Architectural Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (48, 6, 'Class', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (49, 6, 'Method', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (50, 6, 'Mixin', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (51, 6, 'Namespace', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (52, 6, 'Package', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (53, 6, 'Name Mangling', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (54, 6, 'Data Driven Design', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (55, 6, 'Cohesion', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (56, 6, 'Coupling', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (57, 6, 'Inheritance', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (58, 6, 'Polymorphism', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (59, 6, 'Runtime Type Information', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (60, 6, 'Resource Acquisition Is Initialization', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (61, 6, 'Meta Programming', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (62, 6, 'Type System', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (63, 8, 'Memory', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (64, 8, 'Process', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (65, 8, 'Interrupt', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (66, 8, 'Time', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (67, 8, 'System Call', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (68, 8, 'Signal', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (69, 8, 'Filesystem', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (70, 8, 'Posix', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (71, 9, 'DMZ', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (72, 9, 'Firewall', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (73, 9, 'Load Balancer', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (74, 9, 'Network Protocol', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (75, 9, 'Network Programming', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (76, 9, 'Cloud', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (77, 9, 'Distributed System', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (78, 10, 'Cryptography', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (79, 11, 'Load Balancing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (80, 11, 'Uptime', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (81, 11, 'Downtime', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (82, 11, 'Service Level Agreement', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (83, 11, 'Failover', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (84, 11, 'Disaster Recovery', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (85, 11, 'Redundancy', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (86, 11, 'Fault Tolerant', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (87, 11, 'Reliability', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (88, 11, 'Cluster', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (89, 11, 'Single Point of Failure', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (90, 12, 'Horizontal Scaling', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (91, 12, 'Vertical Scaling', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (92, 12, 'Database Scaling', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (93, 13, 'Structured Query Language', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (94, 13, 'Extract, Transform, and Load', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (95, 13, 'Data Warehouse', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (96, 13, 'Online Transaction Processing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (97, 13, 'Online Analytical Processing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (98, 13, 'Multidimensional Cube', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (99, 13, 'Hyper Cube', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (100, 13, 'Data Mining', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (101, 13, 'Table', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (102, 13, 'Stored Procedure', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (103, 13, 'Database Index', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (104, 13, 'Tuple', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (105, 13, 'Row', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (106, 13, 'Attribute', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (107, 13, 'Column', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (108, 13, 'Domain Model', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (109, 13, 'Data Model', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (110, 13, 'Entity Relationship Modeling', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (111, 13, 'Schema', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (112, 13, 'Constraint', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (113, 13, 'Relational Database', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (114, 13, 'Object Relational Mapping', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (115, 13, 'Normalization', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (116, 13, 'Denormalization', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (117, 13, 'Normal Form', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (118, 13, 'Priimary Key', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (119, 13, 'Foreign Key', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (120, 13, 'Cardinality', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (121, 13, 'NoSQL Database', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (122, 13, 'Document Database', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (123, 13, 'ACID', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (124, 13, 'BASE', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (125, 13, 'Transaction', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (126, 13, 'Transaction Isolation', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (127, 13, 'Transaction Isolation Level', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (128, 13, 'Read Phenomena', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (129, 13, 'Durability', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (130, 14, 'Bubble Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (131, 14, 'Quick Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (132, 14, 'Insertion Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (133, 14, 'Merge Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (134, 14, 'Heap Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (135, 14, 'Selection Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (136, 14, 'Radix Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (137, 14, 'Bucket Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (138, 15, 'Breadth First Search', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (139, 15, 'Depth First Search', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (140, 15, 'Best First Search', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (141, 15, 'Dijkstra''s Algorithm', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (142, 15, 'Bellman-Ford Algorithm', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (143, 15, 'Toplogical Sort', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (144, 16, 'NP-hard', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (145, 16, 'NP-complete', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (146, 16, 'NP', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (147, 16, 'O(1)', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (148, 16, 'O(logn)', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (149, 16, 'O(nlogn)', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (150, 16, 'O(n^2)', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (151, 16, 'O(n!)', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (152, 16, 'Asymptotic Analysis', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (153, 16, 'Big O Notation', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (154, 16, 'Omega Notation', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (155, 16, 'Theta Notation', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (156, 16, 'Polynomial Time', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (157, 16, 'Computational Complexity', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (158, 16, 'Time Complexity', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (159, 16, 'Space Complexity', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (160, 44, 'Lock', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (161, 44, 'Spin Lock', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (162, 44, 'Semaphore', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (163, 44, 'Mutex', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (164, 44, 'Conditional Variable', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (165, 45, 'Creational Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (166, 45, 'Structural Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (167, 46, 'Chain of Responsibility', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (168, 46, 'Command Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (169, 46, 'Interpreter Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (170, 46, 'Iterator Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (171, 46, 'Mediator Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (172, 46, 'Memento Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (173, 46, 'Observer Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (174, 46, 'State Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (175, 46, 'Strategy Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (176, 46, 'Template Method', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (177, 46, 'Visitor Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (178, 47, 'Data Source Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (179, 47, 'Presentation Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (180, 47, 'Distribution Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (181, 48, 'Class Hierarchy', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (182, 48, 'Class Method', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (183, 48, 'Abstract Class', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (184, 48, 'Inner Class', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (185, 48, 'Base Class', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (186, 48, 'Subclass', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (187, 48, 'Super Class', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (188, 49, 'Abstract Method', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (189, 49, 'Static Method', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (190, 49, 'Virtual Method', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (191, 49, 'Virtual Function', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (192, 49, 'Method Binding', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (193, 49, 'Dynamic Binding', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (194, 49, 'Multiple Dispatch', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (195, 57, 'Multiple Inheritance', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (196, 57, 'Virtual Inheritance', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (197, 61, 'Meta Class', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (198, 62, 'Type Checking', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (199, 62, 'Static Typing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (200, 62, 'Dynamic Typing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (201, 62, 'Strong  Typing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (202, 62, 'Weaking Typing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (203, 62, 'Duck Typing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (204, 63, 'Virtual Memory', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (205, 63, 'Random Access Memory', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (206, 63, 'Logical Address', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (207, 63, 'Physical Address', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (208, 63, 'Memory Management Unit', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (209, 63, 'Direct Memory Access', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (210, 63, 'Paging', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (211, 63, 'Physical Address Extension', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (212, 63, 'Swapping', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (213, 63, 'Shared Memory', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (214, 64, 'Lightweight Process', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (215, 64, 'Zombie Process', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (216, 64, 'Address Space', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (217, 64, 'Daemon Process', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (218, 64, 'Multiprocess', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (219, 64, 'Interprocess Communication', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (220, 65, 'Interrupt Request', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (221, 66, 'Real Time Clock', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (222, 66, 'jiffies', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (223, 67, 'brk()', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (224, 67, 'fork()', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (225, 67, 'vfork()', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (226, 68, 'SIGHUP', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (227, 68, 'SIGINT', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (228, 68, 'SIGQUIT', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (229, 68, 'SIGKILL', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (230, 68, 'SIGPIPE', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (231, 68, 'SIGALRM', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (232, 68, 'SIGTERM', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (233, 68, 'SIGCHLD', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (234, 68, 'Signal Handler', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (235, 69, 'File Descriptor', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (236, 69, 'ext2', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (237, 69, 'ext3', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (238, 69, 'ext4', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (239, 69, 'ReiserFS', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (240, 69, 'Reiser4', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (241, 74, 'IP', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (242, 74, 'TCP', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (243, 74, 'TCP/IP', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (244, 74, 'UDP', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (245, 74, 'HTTP', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (246, 74, 'HTTPS', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (247, 74, 'DNS', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (248, 74, 'IPv4', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (249, 74, 'IPv6', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (250, 74, 'Multicast', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (251, 74, 'Pragmatic General Multicast', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (252, 75, 'Socket', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (253, 75, 'Secure Socket Layer', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (254, 75, 'Transport Layer Security', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (255, 75, 'I/O Multiplexing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (256, 75, 'Synchronous I/O', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (257, 75, 'Asynchronous I/O', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (258, 75, 'Blocking I/O', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (259, 75, 'Nonblocking I/O', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (260, 75, 'Unix Domain Socket', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (261, 77, 'Client', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (262, 77, 'Server', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (263, 77, 'Client-Server', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (264, 77, '3 Tier Architecture', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (265, 77, 'n Tier Architecture', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (266, 77, 'Peer to Peer', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (267, 77, 'Space Based Architecture', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (268, 77, 'Colocated', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (269, 77, 'In Memory Datagrid', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (270, 77, 'Master', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (271, 77, 'Slave', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (272, 77, 'Master-Slave', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (273, 77, 'Message Passing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (274, 77, 'Distributed Computing', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (275, 77, 'Halting Problem', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (276, 77, 'Thundering Herd', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (277, 77, 'Brewer''s CAP Theorem', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (278, 77, 'Consistency', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (279, 77, 'Availability', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (280, 77, 'Network Partition', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (281, 77, 'Partition Tolerance', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (282, 77, 'Service Oriented Architecture', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (283, 77, 'Software as a Service', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (284, 77, 'Sharding', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (285, 77, 'Primary', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (286, 77, 'Backup', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (287, 78, 'Public Key Infrastructure', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (288, 78, 'Public Key', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (289, 78, 'Private Key', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (290, 78, 'Public Key Cryptography', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (291, 78, 'Symmetric Key Cryptography', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (292, 78, 'Plaintext', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (293, 78, 'Key', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (294, 78, 'Diffie-Hellman Key Exchange', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (295, 78, 'Cipher', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (296, 78, 'Hash Function', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (297, 78, 'Salt', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (298, 101, 'Associative Table', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (299, 101, 'Fact Table', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (300, 101, 'Dimension Table', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (301, 109, 'Association', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (302, 111, 'Multidimension Schema', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (303, 111, 'Star Schema', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (304, 111, 'Snowflake Schema', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (305, 112, 'Unique Constraint', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (306, 112, 'Check Constraint', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (307, 112, 'Not NULL Constraint', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (308, 112, 'Primary Key Constraint', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (309, 112, 'Foreign Key Constraint', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (310, 117, 'First Normal Form', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (311, 117, 'Second Normal Form', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (312, 117, 'Third Normal Form', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (313, 113, 'Postgresql', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (314, 113, 'MySQL', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (315, 113, 'Oracle', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (316, 127, 'Serializable', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (317, 127, 'Repeatable Read', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (318, 127, 'Read Committed', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (319, 127, 'Read Uncommitted', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (320, 128, 'Dirty Read', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (321, 128, 'Non-repeatable Read', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (322, 128, 'Phantom Read', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (323, 165, 'Abstract Factory', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (324, 165, 'Builder Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (325, 165, 'Factory Method', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (326, 165, 'Prototype Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (327, 165, 'Singleton', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (328, 166, 'Adapter Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (329, 166, 'Bridge Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (330, 166, 'Composite Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (331, 166, 'Decorator Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (332, 166, 'Facade Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (333, 166, 'Flyweight Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (334, 166, 'Proxy Design Pattern', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (335, 178, 'Active Record', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (336, 178, 'Table Data Gateway', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (337, 178, 'Row Data Gateway', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (338, 178, 'Data Mapper', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (339, 179, 'Model View Controller', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (340, 180, 'Data Transfer Object', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (341, 216, 'User Mode', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (342, 216, 'Kernel Model', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (343, 219, 'IPC Messages', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (344, 219, 'IPC Shared Memory', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (345, 219, 'Pipe', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (346, 219, 'Named Pipe', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (347, 219, 'FIFO', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (348, 219, 'Message Queue', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (349, 287, 'Certificate Authority', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (350, 287, 'Certificate', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (351, 295, 'Symmetric Key Cipher', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (352, 296, 'Cryptographic Hash Function', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (353, 301, 'One To One', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (354, 301, 'One To Many', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (355, 301, 'Many To Many', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (356, 351, 'Block Cipher', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (357, 351, 'Stream Cipher', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (358, 352, 'Bcrypt', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (359, 352, 'MD5', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (360, 352, 'SHA-1', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (361, 352, 'SHA-256', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (362, 352, 'SHA-512', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (363, 356, 'Data Encryption Standard', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (364, 356, 'RC5', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (365, 356, 'Advanced Encryption Standard', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (366, 356, 'Blowfish', '');
INSERT INTO concept (id, parent_id, name, description) VALUES (367, 357, 'RC4', '');

SELECT setval('concept_id_seq', (SELECT max(id) FROM concept));
