INSERT INTO tag (id, name, concept_id) VALUES (1, 'Software', 1);
INSERT INTO tag (id, name, concept_id) VALUES (2, 'Algorithm', 2);
INSERT INTO tag (id, name, concept_id) VALUES (3, 'Sorting Algorithm', 14);
INSERT INTO tag (id, name, concept_id) VALUES (4, 'Bubble Sort', 130);
INSERT INTO tag (id, name, concept_id) VALUES (5, 'Quick Sort', 131);
INSERT INTO tag (id, name, concept_id) VALUES (6, 'Insertion Sort', 132);
INSERT INTO tag (id, name, concept_id) VALUES (7, 'Merge Sort', 133);
INSERT INTO tag (id, name, concept_id) VALUES (8, 'Heap Sort', 134);
INSERT INTO tag (id, name, concept_id) VALUES (9, 'Selection Sort', 135);
INSERT INTO tag (id, name, concept_id) VALUES (10, 'Radix Sort', 136);
INSERT INTO tag (id, name, concept_id) VALUES (11, 'Bucket Sort', 137);
INSERT INTO tag (id, name, concept_id) VALUES (12, 'Graph Algorithm', 15);
INSERT INTO tag (id, name, concept_id) VALUES (13, 'Breadth First Search', 138);
INSERT INTO tag (id, name, concept_id) VALUES (14, 'BFS', 138);
INSERT INTO tag (id, name, concept_id) VALUES (15, 'Depth First Search', 139);
INSERT INTO tag (id, name, concept_id) VALUES (16, 'DFS', 139);
INSERT INTO tag (id, name, concept_id) VALUES (17, 'Best First Search', 140);
INSERT INTO tag (id, name, concept_id) VALUES (18, 'Dijkstra''s Algorithm', 141);
INSERT INTO tag (id, name, concept_id) VALUES (19, 'Bellman-Ford Algorithm', 142);
INSERT INTO tag (id, name, concept_id) VALUES (20, 'Toplogical Sort', 143);
INSERT INTO tag (id, name, concept_id) VALUES (21, 'Algorithmic Complexity', 16);
INSERT INTO tag (id, name, concept_id) VALUES (22, 'NP-hard', 144);
INSERT INTO tag (id, name, concept_id) VALUES (23, 'NP-complete', 145);
INSERT INTO tag (id, name, concept_id) VALUES (24, 'NP', 146);
INSERT INTO tag (id, name, concept_id) VALUES (25, 'O(1)', 147);
INSERT INTO tag (id, name, concept_id) VALUES (26, 'O(logn)', 148);
INSERT INTO tag (id, name, concept_id) VALUES (27, 'O(nlogn)', 149);
INSERT INTO tag (id, name, concept_id) VALUES (28, 'O(n^2)', 150);
INSERT INTO tag (id, name, concept_id) VALUES (29, 'O(n!)', 151);
INSERT INTO tag (id, name, concept_id) VALUES (30, 'Asymptotic Analysis', 152);
INSERT INTO tag (id, name, concept_id) VALUES (31, 'Big O Notation', 153);
INSERT INTO tag (id, name, concept_id) VALUES (32, 'Omega Notation', 154);
INSERT INTO tag (id, name, concept_id) VALUES (33, 'Theta Notation', 155);
INSERT INTO tag (id, name, concept_id) VALUES (34, 'Polynomial Time', 156);
INSERT INTO tag (id, name, concept_id) VALUES (35, 'Computational Complexity', 157);
INSERT INTO tag (id, name, concept_id) VALUES (36, 'Time Complexity', 158);
INSERT INTO tag (id, name, concept_id) VALUES (37, 'Space Complexity', 159);
INSERT INTO tag (id, name, concept_id) VALUES (38, 'Data Structures', 3);
INSERT INTO tag (id, name, concept_id) VALUES (39, 'Stack', 17);
INSERT INTO tag (id, name, concept_id) VALUES (40, 'Queue', 18);
INSERT INTO tag (id, name, concept_id) VALUES (41, 'Linked List', 19);
INSERT INTO tag (id, name, concept_id) VALUES (42, 'Hash Table', 20);
INSERT INTO tag (id, name, concept_id) VALUES (43, 'Binary Search Tree', 21);
INSERT INTO tag (id, name, concept_id) VALUES (44, 'Red Black Tree', 22);
INSERT INTO tag (id, name, concept_id) VALUES (45, 'B Tree', 23);
INSERT INTO tag (id, name, concept_id) VALUES (46, 'Heap', 24);
INSERT INTO tag (id, name, concept_id) VALUES (47, 'Binomial Heap', 25);
INSERT INTO tag (id, name, concept_id) VALUES (48, 'Fibonacci Heap', 26);
INSERT INTO tag (id, name, concept_id) VALUES (49, 'Graph', 27);
INSERT INTO tag (id, name, concept_id) VALUES (50, 'Directed Graph', 28);
INSERT INTO tag (id, name, concept_id) VALUES (51, 'Directed Acyclic Graph', 29);
INSERT INTO tag (id, name, concept_id) VALUES (52, 'Adjacency List', 30);
INSERT INTO tag (id, name, concept_id) VALUES (53, 'Adjacency Matrix', 31);
INSERT INTO tag (id, name, concept_id) VALUES (54, 'Concurrency', 4);
INSERT INTO tag (id, name, concept_id) VALUES (55, 'Parallel Computing', 32);
INSERT INTO tag (id, name, concept_id) VALUES (56, 'Atomicity', 33);
INSERT INTO tag (id, name, concept_id) VALUES (57, 'Atomic', 34);
INSERT INTO tag (id, name, concept_id) VALUES (58, 'Multiversion Concurrency Control', 35);
INSERT INTO tag (id, name, concept_id) VALUES (59, 'MVCC', 35);
INSERT INTO tag (id, name, concept_id) VALUES (60, 'MCC', 35);
INSERT INTO tag (id, name, concept_id) VALUES (61, 'Optimistic Locking', 36);
INSERT INTO tag (id, name, concept_id) VALUES (62, 'Pessimistic Locking', 37);
INSERT INTO tag (id, name, concept_id) VALUES (63, 'Two Phase Locking', 38);
INSERT INTO tag (id, name, concept_id) VALUES (64, 'Multithreaded', 39);
INSERT INTO tag (id, name, concept_id) VALUES (65, 'Criticial Section', 40);
INSERT INTO tag (id, name, concept_id) VALUES (66, 'Preemption', 41);
INSERT INTO tag (id, name, concept_id) VALUES (67, 'Race Condition', 42);
INSERT INTO tag (id, name, concept_id) VALUES (68, 'Deadlock', 43);
INSERT INTO tag (id, name, concept_id) VALUES (69, 'Syncrhonization', 44);
INSERT INTO tag (id, name, concept_id) VALUES (70, 'Lock', 160);
INSERT INTO tag (id, name, concept_id) VALUES (71, 'Spin Lock', 161);
INSERT INTO tag (id, name, concept_id) VALUES (72, 'Semaphore', 162);
INSERT INTO tag (id, name, concept_id) VALUES (73, 'Mutex', 163);
INSERT INTO tag (id, name, concept_id) VALUES (74, 'Conditional Variable', 164);
INSERT INTO tag (id, name, concept_id) VALUES (75, 'Design Pattern', 5);
INSERT INTO tag (id, name, concept_id) VALUES (76, 'Object Oriented Design Pattern', 45);
INSERT INTO tag (id, name, concept_id) VALUES (77, 'Creational Design Pattern', 165);
INSERT INTO tag (id, name, concept_id) VALUES (78, 'Abstract Factory', 323);
INSERT INTO tag (id, name, concept_id) VALUES (79, 'Builder Design Pattern', 324);
INSERT INTO tag (id, name, concept_id) VALUES (80, 'Factory Method', 325);
INSERT INTO tag (id, name, concept_id) VALUES (81, 'Prototype Design Pattern', 326);
INSERT INTO tag (id, name, concept_id) VALUES (82, 'Singleton', 327);
INSERT INTO tag (id, name, concept_id) VALUES (83, 'Structural Design Pattern', 166);
INSERT INTO tag (id, name, concept_id) VALUES (84, 'Adapter Design Pattern', 328);
INSERT INTO tag (id, name, concept_id) VALUES (85, 'Bridge Design Pattern', 329);
INSERT INTO tag (id, name, concept_id) VALUES (86, 'Composite Design Pattern', 330);
INSERT INTO tag (id, name, concept_id) VALUES (87, 'Decorator Design Pattern', 331);
INSERT INTO tag (id, name, concept_id) VALUES (88, 'Facade Design Pattern', 332);
INSERT INTO tag (id, name, concept_id) VALUES (89, 'Flyweight Design Pattern', 333);
INSERT INTO tag (id, name, concept_id) VALUES (90, 'Proxy Design Pattern', 334);
INSERT INTO tag (id, name, concept_id) VALUES (91, 'Behavioral Design Pattern', 46);
INSERT INTO tag (id, name, concept_id) VALUES (92, 'Chain of Responsibility', 167);
INSERT INTO tag (id, name, concept_id) VALUES (93, 'Command Design Pattern', 168);
INSERT INTO tag (id, name, concept_id) VALUES (94, 'Interpreter Design Pattern', 169);
INSERT INTO tag (id, name, concept_id) VALUES (95, 'Iterator Design Pattern', 170);
INSERT INTO tag (id, name, concept_id) VALUES (96, 'Mediator Design Pattern', 171);
INSERT INTO tag (id, name, concept_id) VALUES (97, 'Memento Design Pattern', 172);
INSERT INTO tag (id, name, concept_id) VALUES (98, 'Observer Design Pattern', 173);
INSERT INTO tag (id, name, concept_id) VALUES (99, 'State Design Pattern', 174);
INSERT INTO tag (id, name, concept_id) VALUES (100, 'Strategy Design Pattern', 175);
INSERT INTO tag (id, name, concept_id) VALUES (101, 'Template Method', 176);
INSERT INTO tag (id, name, concept_id) VALUES (102, 'Visitor Design Pattern', 177);
INSERT INTO tag (id, name, concept_id) VALUES (103, 'Architectural Design Pattern', 47);
INSERT INTO tag (id, name, concept_id) VALUES (104, 'Data Source Pattern', 178);
INSERT INTO tag (id, name, concept_id) VALUES (105, 'Active Record', 335);
INSERT INTO tag (id, name, concept_id) VALUES (106, 'Table Data Gateway', 336);
INSERT INTO tag (id, name, concept_id) VALUES (107, 'Row Data Gateway', 337);
INSERT INTO tag (id, name, concept_id) VALUES (108, 'Data Mapper', 338);
INSERT INTO tag (id, name, concept_id) VALUES (109, 'Presentation Pattern', 179);
INSERT INTO tag (id, name, concept_id) VALUES (110, 'Model View Controller', 339);
INSERT INTO tag (id, name, concept_id) VALUES (111, 'Distribution Pattern', 180);
INSERT INTO tag (id, name, concept_id) VALUES (112, 'Data Transfer Object', 340);
INSERT INTO tag (id, name, concept_id) VALUES (113, 'DTO', 340);
INSERT INTO tag (id, name, concept_id) VALUES (114, 'Object Oriented Programming', 6);
INSERT INTO tag (id, name, concept_id) VALUES (115, 'OOP', 6);
INSERT INTO tag (id, name, concept_id) VALUES (116, 'Class', 48);
INSERT INTO tag (id, name, concept_id) VALUES (117, 'Class Hierarchy', 181);
INSERT INTO tag (id, name, concept_id) VALUES (118, 'Class Method', 182);
INSERT INTO tag (id, name, concept_id) VALUES (119, 'Abstract Class', 183);
INSERT INTO tag (id, name, concept_id) VALUES (120, 'Inner Class', 184);
INSERT INTO tag (id, name, concept_id) VALUES (121, 'Base Class', 185);
INSERT INTO tag (id, name, concept_id) VALUES (122, 'Subclass', 186);
INSERT INTO tag (id, name, concept_id) VALUES (123, 'Super Class', 187);
INSERT INTO tag (id, name, concept_id) VALUES (124, 'Method', 49);
INSERT INTO tag (id, name, concept_id) VALUES (125, 'Abstract Method', 188);
INSERT INTO tag (id, name, concept_id) VALUES (126, 'Static Method', 189);
INSERT INTO tag (id, name, concept_id) VALUES (127, 'Virtual Method', 190);
INSERT INTO tag (id, name, concept_id) VALUES (128, 'Virtual Function', 191);
INSERT INTO tag (id, name, concept_id) VALUES (129, 'Method Binding', 192);
INSERT INTO tag (id, name, concept_id) VALUES (130, 'Dynamic Binding', 193);
INSERT INTO tag (id, name, concept_id) VALUES (131, 'Multiple Dispatch', 194);
INSERT INTO tag (id, name, concept_id) VALUES (132, 'Mixin', 50);
INSERT INTO tag (id, name, concept_id) VALUES (133, 'Namespace', 51);
INSERT INTO tag (id, name, concept_id) VALUES (134, 'Package', 52);
INSERT INTO tag (id, name, concept_id) VALUES (135, 'Name Mangling', 53);
INSERT INTO tag (id, name, concept_id) VALUES (136, 'Data Driven Design', 54);
INSERT INTO tag (id, name, concept_id) VALUES (137, 'Cohesion', 55);
INSERT INTO tag (id, name, concept_id) VALUES (138, 'Coupling', 56);
INSERT INTO tag (id, name, concept_id) VALUES (139, 'Inheritance', 57);
INSERT INTO tag (id, name, concept_id) VALUES (140, 'Multiple Inheritance', 195);
INSERT INTO tag (id, name, concept_id) VALUES (141, 'Virtual Inheritance', 196);
INSERT INTO tag (id, name, concept_id) VALUES (142, 'Polymorphism', 58);
INSERT INTO tag (id, name, concept_id) VALUES (143, 'Runtime Type Information', 59);
INSERT INTO tag (id, name, concept_id) VALUES (144, 'RTTI', 59);
INSERT INTO tag (id, name, concept_id) VALUES (145, 'Resource Acquisition Is Initialization', 60);
INSERT INTO tag (id, name, concept_id) VALUES (146, 'RAII', 60);
INSERT INTO tag (id, name, concept_id) VALUES (147, 'Meta Programming', 61);
INSERT INTO tag (id, name, concept_id) VALUES (148, 'Meta Class', 197);
INSERT INTO tag (id, name, concept_id) VALUES (149, 'Type System', 62);
INSERT INTO tag (id, name, concept_id) VALUES (150, 'Type Checking', 198);
INSERT INTO tag (id, name, concept_id) VALUES (151, 'Static Typing', 199);
INSERT INTO tag (id, name, concept_id) VALUES (152, 'Dynamic Typing', 200);
INSERT INTO tag (id, name, concept_id) VALUES (153, 'Strong  Typing', 201);
INSERT INTO tag (id, name, concept_id) VALUES (154, 'Weaking Typing', 202);
INSERT INTO tag (id, name, concept_id) VALUES (155, 'Duck Typing', 203);
INSERT INTO tag (id, name, concept_id) VALUES (156, 'Functional Programming', 7);
INSERT INTO tag (id, name, concept_id) VALUES (157, 'Operating System', 8);
INSERT INTO tag (id, name, concept_id) VALUES (158, 'OS', 8);
INSERT INTO tag (id, name, concept_id) VALUES (159, 'Memory', 63);
INSERT INTO tag (id, name, concept_id) VALUES (160, 'Virtual Memory', 204);
INSERT INTO tag (id, name, concept_id) VALUES (161, 'Random Access Memory', 205);
INSERT INTO tag (id, name, concept_id) VALUES (162, 'RAM', 205);
INSERT INTO tag (id, name, concept_id) VALUES (163, 'Logical Address', 206);
INSERT INTO tag (id, name, concept_id) VALUES (164, 'Physical Address', 207);
INSERT INTO tag (id, name, concept_id) VALUES (165, 'Memory Management Unit', 208);
INSERT INTO tag (id, name, concept_id) VALUES (166, 'Direct Memory Access', 209);
INSERT INTO tag (id, name, concept_id) VALUES (167, 'Paging', 210);
INSERT INTO tag (id, name, concept_id) VALUES (168, 'Physical Address Extension', 211);
INSERT INTO tag (id, name, concept_id) VALUES (169, 'PAE', 211);
INSERT INTO tag (id, name, concept_id) VALUES (170, 'Swapping', 212);
INSERT INTO tag (id, name, concept_id) VALUES (171, 'Shared Memory', 213);
INSERT INTO tag (id, name, concept_id) VALUES (172, 'Process', 64);
INSERT INTO tag (id, name, concept_id) VALUES (173, 'Lightweight Process', 214);
INSERT INTO tag (id, name, concept_id) VALUES (174, 'LWP', 214);
INSERT INTO tag (id, name, concept_id) VALUES (175, 'Zombie Process', 215);
INSERT INTO tag (id, name, concept_id) VALUES (176, 'Address Space', 216);
INSERT INTO tag (id, name, concept_id) VALUES (177, 'Daemon Process', 217);
INSERT INTO tag (id, name, concept_id) VALUES (178, 'User Mode', 341);
INSERT INTO tag (id, name, concept_id) VALUES (179, 'Kernel Model', 342);
INSERT INTO tag (id, name, concept_id) VALUES (180, 'Multiprocess', 218);
INSERT INTO tag (id, name, concept_id) VALUES (181, 'Interprocess Communication', 219);
INSERT INTO tag (id, name, concept_id) VALUES (182, 'IPC', 219);
INSERT INTO tag (id, name, concept_id) VALUES (183, 'IPC Messages', 343);
INSERT INTO tag (id, name, concept_id) VALUES (184, 'IPC Shared Memory', 344);
INSERT INTO tag (id, name, concept_id) VALUES (185, 'Pipe', 345);
INSERT INTO tag (id, name, concept_id) VALUES (186, 'Named Pipe', 346);
INSERT INTO tag (id, name, concept_id) VALUES (187, 'FIFO', 347);
INSERT INTO tag (id, name, concept_id) VALUES (188, 'Message Queue', 348);
INSERT INTO tag (id, name, concept_id) VALUES (189, 'Interrupt', 65);
INSERT INTO tag (id, name, concept_id) VALUES (190, 'Interrupt Request', 220);
INSERT INTO tag (id, name, concept_id) VALUES (191, 'IRQ', 220);
INSERT INTO tag (id, name, concept_id) VALUES (192, 'Time', 66);
INSERT INTO tag (id, name, concept_id) VALUES (193, 'Real Time Clock', 221);
INSERT INTO tag (id, name, concept_id) VALUES (194, 'jiffies', 222);
INSERT INTO tag (id, name, concept_id) VALUES (195, 'System Call', 67);
INSERT INTO tag (id, name, concept_id) VALUES (196, 'brk()', 223);
INSERT INTO tag (id, name, concept_id) VALUES (197, 'fork()', 224);
INSERT INTO tag (id, name, concept_id) VALUES (198, 'vfork()', 225);
INSERT INTO tag (id, name, concept_id) VALUES (199, 'Signal', 68);
INSERT INTO tag (id, name, concept_id) VALUES (200, 'SIGHUP', 226);
INSERT INTO tag (id, name, concept_id) VALUES (201, 'SIGINT', 227);
INSERT INTO tag (id, name, concept_id) VALUES (202, 'SIGQUIT', 228);
INSERT INTO tag (id, name, concept_id) VALUES (203, 'SIGKILL', 229);
INSERT INTO tag (id, name, concept_id) VALUES (204, 'SIGPIPE', 230);
INSERT INTO tag (id, name, concept_id) VALUES (205, 'SIGALRM', 231);
INSERT INTO tag (id, name, concept_id) VALUES (206, 'SIGTERM', 232);
INSERT INTO tag (id, name, concept_id) VALUES (207, 'SIGCHLD', 233);
INSERT INTO tag (id, name, concept_id) VALUES (208, 'Signal Handler', 234);
INSERT INTO tag (id, name, concept_id) VALUES (209, 'Filesystem', 69);
INSERT INTO tag (id, name, concept_id) VALUES (210, 'File Descriptor', 235);
INSERT INTO tag (id, name, concept_id) VALUES (211, 'ext2', 236);
INSERT INTO tag (id, name, concept_id) VALUES (212, 'ext3', 237);
INSERT INTO tag (id, name, concept_id) VALUES (213, 'ext4', 238);
INSERT INTO tag (id, name, concept_id) VALUES (214, 'ReiserFS', 239);
INSERT INTO tag (id, name, concept_id) VALUES (215, 'Reiser4', 240);
INSERT INTO tag (id, name, concept_id) VALUES (216, 'Posix', 70);
INSERT INTO tag (id, name, concept_id) VALUES (217, 'Network', 9);
INSERT INTO tag (id, name, concept_id) VALUES (218, 'DMZ', 71);
INSERT INTO tag (id, name, concept_id) VALUES (219, 'Firewall', 72);
INSERT INTO tag (id, name, concept_id) VALUES (220, 'Load Balancer', 73);
INSERT INTO tag (id, name, concept_id) VALUES (221, 'Network Protocol', 74);
INSERT INTO tag (id, name, concept_id) VALUES (222, 'IP', 241);
INSERT INTO tag (id, name, concept_id) VALUES (223, 'TCP', 242);
INSERT INTO tag (id, name, concept_id) VALUES (224, 'TCP/IP', 243);
INSERT INTO tag (id, name, concept_id) VALUES (225, 'UDP', 244);
INSERT INTO tag (id, name, concept_id) VALUES (226, 'HTTP', 245);
INSERT INTO tag (id, name, concept_id) VALUES (227, 'HTTPS', 246);
INSERT INTO tag (id, name, concept_id) VALUES (228, 'DNS', 247);
INSERT INTO tag (id, name, concept_id) VALUES (229, 'IPv4', 248);
INSERT INTO tag (id, name, concept_id) VALUES (230, 'IPv6', 249);
INSERT INTO tag (id, name, concept_id) VALUES (231, 'Multicast', 250);
INSERT INTO tag (id, name, concept_id) VALUES (232, 'Pragmatic General Multicast', 251);
INSERT INTO tag (id, name, concept_id) VALUES (233, 'Network Programming', 75);
INSERT INTO tag (id, name, concept_id) VALUES (234, 'Socket', 252);
INSERT INTO tag (id, name, concept_id) VALUES (235, 'Secure Socket Layer', 253);
INSERT INTO tag (id, name, concept_id) VALUES (236, 'Transport Layer Security', 254);
INSERT INTO tag (id, name, concept_id) VALUES (237, 'I/O Multiplexing', 255);
INSERT INTO tag (id, name, concept_id) VALUES (238, 'Synchronous I/O', 256);
INSERT INTO tag (id, name, concept_id) VALUES (239, 'Asynchronous I/O', 257);
INSERT INTO tag (id, name, concept_id) VALUES (240, 'Blocking I/O', 258);
INSERT INTO tag (id, name, concept_id) VALUES (241, 'Nonblocking I/O', 259);
INSERT INTO tag (id, name, concept_id) VALUES (242, 'Unix Domain Socket', 260);
INSERT INTO tag (id, name, concept_id) VALUES (243, 'Cloud', 76);
INSERT INTO tag (id, name, concept_id) VALUES (244, 'Distributed System', 77);
INSERT INTO tag (id, name, concept_id) VALUES (245, 'Client', 261);
INSERT INTO tag (id, name, concept_id) VALUES (246, 'Server', 262);
INSERT INTO tag (id, name, concept_id) VALUES (247, 'Client-Server', 263);
INSERT INTO tag (id, name, concept_id) VALUES (248, '3 Tier Architecture', 264);
INSERT INTO tag (id, name, concept_id) VALUES (249, 'n Tier Architecture', 265);
INSERT INTO tag (id, name, concept_id) VALUES (250, 'Peer to Peer', 266);
INSERT INTO tag (id, name, concept_id) VALUES (251, 'Space Based Architecture', 267);
INSERT INTO tag (id, name, concept_id) VALUES (252, 'Colocated', 268);
INSERT INTO tag (id, name, concept_id) VALUES (253, 'In Memory Datagrid', 269);
INSERT INTO tag (id, name, concept_id) VALUES (254, 'Master', 270);
INSERT INTO tag (id, name, concept_id) VALUES (255, 'Slave', 271);
INSERT INTO tag (id, name, concept_id) VALUES (256, 'Master-Slave', 272);
INSERT INTO tag (id, name, concept_id) VALUES (257, 'Message Passing', 273);
INSERT INTO tag (id, name, concept_id) VALUES (258, 'Distributed Computing', 274);
INSERT INTO tag (id, name, concept_id) VALUES (259, 'Halting Problem', 275);
INSERT INTO tag (id, name, concept_id) VALUES (260, 'Thundering Herd', 276);
INSERT INTO tag (id, name, concept_id) VALUES (261, 'Brewer''s CAP Theorem', 277);
INSERT INTO tag (id, name, concept_id) VALUES (262, 'Consistency', 278);
INSERT INTO tag (id, name, concept_id) VALUES (263, 'Availability', 279);
INSERT INTO tag (id, name, concept_id) VALUES (264, 'Network Partition', 280);
INSERT INTO tag (id, name, concept_id) VALUES (265, 'Partition Tolerance', 281);
INSERT INTO tag (id, name, concept_id) VALUES (266, 'Service Oriented Architecture', 282);
INSERT INTO tag (id, name, concept_id) VALUES (267, 'SOA', 282);
INSERT INTO tag (id, name, concept_id) VALUES (268, 'Software as a Service', 283);
INSERT INTO tag (id, name, concept_id) VALUES (269, 'SaaS', 283);
INSERT INTO tag (id, name, concept_id) VALUES (270, 'Sharding', 284);
INSERT INTO tag (id, name, concept_id) VALUES (271, 'Primary', 285);
INSERT INTO tag (id, name, concept_id) VALUES (272, 'Backup', 286);
INSERT INTO tag (id, name, concept_id) VALUES (273, 'Security', 10);
INSERT INTO tag (id, name, concept_id) VALUES (274, 'Cryptography', 78);
INSERT INTO tag (id, name, concept_id) VALUES (275, 'Public Key Infrastructure', 287);
INSERT INTO tag (id, name, concept_id) VALUES (276, 'Certificate Authority', 349);
INSERT INTO tag (id, name, concept_id) VALUES (277, 'Certificate', 350);
INSERT INTO tag (id, name, concept_id) VALUES (278, 'Public Key', 288);
INSERT INTO tag (id, name, concept_id) VALUES (279, 'Private Key', 289);
INSERT INTO tag (id, name, concept_id) VALUES (280, 'Public Key Cryptography', 290);
INSERT INTO tag (id, name, concept_id) VALUES (281, 'Symmetric Key Cryptography', 291);
INSERT INTO tag (id, name, concept_id) VALUES (282, 'Plaintext', 292);
INSERT INTO tag (id, name, concept_id) VALUES (283, 'Key', 293);
INSERT INTO tag (id, name, concept_id) VALUES (284, 'Diffie-Hellman Key Exchange', 294);
INSERT INTO tag (id, name, concept_id) VALUES (285, 'Cipher', 295);
INSERT INTO tag (id, name, concept_id) VALUES (286, 'Symmetric Key Cipher', 351);
INSERT INTO tag (id, name, concept_id) VALUES (287, 'Block Cipher', 356);
INSERT INTO tag (id, name, concept_id) VALUES (288, 'Data Encryption Standard', 363);
INSERT INTO tag (id, name, concept_id) VALUES (289, 'DES', 363);
INSERT INTO tag (id, name, concept_id) VALUES (290, 'RC5', 364);
INSERT INTO tag (id, name, concept_id) VALUES (291, 'Advanced Encryption Standard', 365);
INSERT INTO tag (id, name, concept_id) VALUES (292, 'AES', 365);
INSERT INTO tag (id, name, concept_id) VALUES (293, 'Blowfish', 366);
INSERT INTO tag (id, name, concept_id) VALUES (294, 'Stream Cipher', 357);
INSERT INTO tag (id, name, concept_id) VALUES (295, 'RC4', 367);
INSERT INTO tag (id, name, concept_id) VALUES (296, 'Hash Function', 296);
INSERT INTO tag (id, name, concept_id) VALUES (297, 'Cryptographic Hash Function', 352);
INSERT INTO tag (id, name, concept_id) VALUES (298, 'Bcrypt', 358);
INSERT INTO tag (id, name, concept_id) VALUES (299, 'MD5', 359);
INSERT INTO tag (id, name, concept_id) VALUES (300, 'SHA-1', 360);
INSERT INTO tag (id, name, concept_id) VALUES (301, 'SHA-256', 361);
INSERT INTO tag (id, name, concept_id) VALUES (302, 'SHA-512', 362);
INSERT INTO tag (id, name, concept_id) VALUES (303, 'Salt', 297);
INSERT INTO tag (id, name, concept_id) VALUES (304, 'High Availability', 11);
INSERT INTO tag (id, name, concept_id) VALUES (305, 'Load Balancing', 79);
INSERT INTO tag (id, name, concept_id) VALUES (306, 'Uptime', 80);
INSERT INTO tag (id, name, concept_id) VALUES (307, 'Downtime', 81);
INSERT INTO tag (id, name, concept_id) VALUES (308, 'Service Level Agreement', 82);
INSERT INTO tag (id, name, concept_id) VALUES (309, 'Failover', 83);
INSERT INTO tag (id, name, concept_id) VALUES (310, 'Disaster Recovery', 84);
INSERT INTO tag (id, name, concept_id) VALUES (311, 'Redundancy', 85);
INSERT INTO tag (id, name, concept_id) VALUES (312, 'Fault Tolerant', 86);
INSERT INTO tag (id, name, concept_id) VALUES (313, 'Reliability', 87);
INSERT INTO tag (id, name, concept_id) VALUES (314, 'Cluster', 88);
INSERT INTO tag (id, name, concept_id) VALUES (315, 'Single Point of Failure', 89);
INSERT INTO tag (id, name, concept_id) VALUES (316, 'Scalability', 12);
INSERT INTO tag (id, name, concept_id) VALUES (317, 'Horizontal Scaling', 90);
INSERT INTO tag (id, name, concept_id) VALUES (318, 'Vertical Scaling', 91);
INSERT INTO tag (id, name, concept_id) VALUES (319, 'Database Scaling', 92);
INSERT INTO tag (id, name, concept_id) VALUES (320, 'Database', 13);
INSERT INTO tag (id, name, concept_id) VALUES (321, 'Structured Query Language', 93);
INSERT INTO tag (id, name, concept_id) VALUES (322, 'SQL', 93);
INSERT INTO tag (id, name, concept_id) VALUES (323, 'Extract, Transform, and Load', 94);
INSERT INTO tag (id, name, concept_id) VALUES (324, 'ETL', 94);
INSERT INTO tag (id, name, concept_id) VALUES (325, 'Data Warehouse', 95);
INSERT INTO tag (id, name, concept_id) VALUES (326, 'Online Transaction Processing', 96);
INSERT INTO tag (id, name, concept_id) VALUES (327, 'Online Analytical Processing', 97);
INSERT INTO tag (id, name, concept_id) VALUES (328, 'Multidimensional Cube', 98);
INSERT INTO tag (id, name, concept_id) VALUES (329, 'Hyper Cube', 99);
INSERT INTO tag (id, name, concept_id) VALUES (330, 'Data Mining', 100);
INSERT INTO tag (id, name, concept_id) VALUES (331, 'Table', 101);
INSERT INTO tag (id, name, concept_id) VALUES (332, 'Stored Procedure', 102);
INSERT INTO tag (id, name, concept_id) VALUES (333, 'Database Index', 103);
INSERT INTO tag (id, name, concept_id) VALUES (334, 'Associative Table', 298);
INSERT INTO tag (id, name, concept_id) VALUES (335, 'Fact Table', 299);
INSERT INTO tag (id, name, concept_id) VALUES (336, 'Dimension Table', 300);
INSERT INTO tag (id, name, concept_id) VALUES (337, 'Tuple', 104);
INSERT INTO tag (id, name, concept_id) VALUES (338, 'Row', 105);
INSERT INTO tag (id, name, concept_id) VALUES (339, 'Attribute', 106);
INSERT INTO tag (id, name, concept_id) VALUES (340, 'Column', 107);
INSERT INTO tag (id, name, concept_id) VALUES (341, 'Domain Model', 108);
INSERT INTO tag (id, name, concept_id) VALUES (342, 'Data Model', 109);
INSERT INTO tag (id, name, concept_id) VALUES (343, 'Association', 301);
INSERT INTO tag (id, name, concept_id) VALUES (344, 'One To One', 353);
INSERT INTO tag (id, name, concept_id) VALUES (345, 'One To Many', 354);
INSERT INTO tag (id, name, concept_id) VALUES (346, 'Many To Many', 355);
INSERT INTO tag (id, name, concept_id) VALUES (347, 'Entity Relationship Modeling', 110);
INSERT INTO tag (id, name, concept_id) VALUES (348, 'Schema', 111);
INSERT INTO tag (id, name, concept_id) VALUES (349, 'Multidimension Schema', 302);
INSERT INTO tag (id, name, concept_id) VALUES (350, 'Star Schema', 303);
INSERT INTO tag (id, name, concept_id) VALUES (351, 'Snowflake Schema', 304);
INSERT INTO tag (id, name, concept_id) VALUES (352, 'Constraint', 112);
INSERT INTO tag (id, name, concept_id) VALUES (353, 'Unique Constraint', 305);
INSERT INTO tag (id, name, concept_id) VALUES (354, 'Check Constraint', 306);
INSERT INTO tag (id, name, concept_id) VALUES (355, 'Not NULL Constraint', 307);
INSERT INTO tag (id, name, concept_id) VALUES (356, 'Primary Key Constraint', 308);
INSERT INTO tag (id, name, concept_id) VALUES (357, 'Foreign Key Constraint', 309);
INSERT INTO tag (id, name, concept_id) VALUES (358, 'Relational Database', 113);
INSERT INTO tag (id, name, concept_id) VALUES (359, 'Object Relational Mapping', 114);
INSERT INTO tag (id, name, concept_id) VALUES (360, 'Normalization', 115);
INSERT INTO tag (id, name, concept_id) VALUES (361, 'Denormalization', 116);
INSERT INTO tag (id, name, concept_id) VALUES (362, 'Normal Form', 117);
INSERT INTO tag (id, name, concept_id) VALUES (363, 'First Normal Form', 310);
INSERT INTO tag (id, name, concept_id) VALUES (364, 'Second Normal Form', 311);
INSERT INTO tag (id, name, concept_id) VALUES (365, 'Third Normal Form', 312);
INSERT INTO tag (id, name, concept_id) VALUES (366, 'Priimary Key', 118);
INSERT INTO tag (id, name, concept_id) VALUES (367, 'Foreign Key', 119);
INSERT INTO tag (id, name, concept_id) VALUES (368, 'Cardinality', 120);
INSERT INTO tag (id, name, concept_id) VALUES (369, 'Postgresql', 313);
INSERT INTO tag (id, name, concept_id) VALUES (370, 'MySQL', 314);
INSERT INTO tag (id, name, concept_id) VALUES (371, 'Oracle', 315);
INSERT INTO tag (id, name, concept_id) VALUES (372, 'NoSQL Database', 121);
INSERT INTO tag (id, name, concept_id) VALUES (373, 'Document Database', 122);
INSERT INTO tag (id, name, concept_id) VALUES (374, 'ACID', 123);
INSERT INTO tag (id, name, concept_id) VALUES (375, 'BASE', 124);
INSERT INTO tag (id, name, concept_id) VALUES (376, 'Transaction', 125);
INSERT INTO tag (id, name, concept_id) VALUES (377, 'Transaction Isolation', 126);
INSERT INTO tag (id, name, concept_id) VALUES (378, 'Transaction Isolation Level', 127);
INSERT INTO tag (id, name, concept_id) VALUES (379, 'Serializable', 316);
INSERT INTO tag (id, name, concept_id) VALUES (380, 'Repeatable Read', 317);
INSERT INTO tag (id, name, concept_id) VALUES (381, 'Read Committed', 318);
INSERT INTO tag (id, name, concept_id) VALUES (382, 'Read Uncommitted', 319);
INSERT INTO tag (id, name, concept_id) VALUES (383, 'Read Phenomena', 128);
INSERT INTO tag (id, name, concept_id) VALUES (384, 'Dirty Read', 320);
INSERT INTO tag (id, name, concept_id) VALUES (385, 'Non-repeatable Read', 321);
INSERT INTO tag (id, name, concept_id) VALUES (386, 'Phantom Read', 322);
INSERT INTO tag (id, name, concept_id) VALUES (387, 'Durability', 129);

SELECT setval('tag_id_seq', (SELECT max(id) FROM tag));
