
INSERT INTO technology (name, type_id, description) VALUES ('Android SDK', 1, 'Native API for the Android OS');
INSERT INTO technology (name, type_id, description) VALUES ('Blackberry SDK', 1, 'Native API for the Blackberry OS');
INSERT INTO technology (name, type_id, description) VALUES ('Cocoa', 1, 'Native object-oriented API for the Mac OS X operating system');
INSERT INTO technology (name, type_id, description) VALUES ('Django', 1, 'A high-level Python Web framework that encourages rapid development and clean, pragmatic design');
INSERT INTO technology (name, type_id, description) VALUES ('Dynamix', 1, 'An open plug-and-play context framework for Android');
INSERT INTO technology (name, type_id, description) VALUES ('Flex SDK', 1, 'A powerful, open source application framework that allows you to easily build mobile applications as well as traditional applications for browser and desktop using the same programming model, tool, and codebase');
INSERT INTO technology (name, type_id, description) VALUES ('Grails', 1, 'An open source, full stack, web application framework for the JVM that uses the Groovy programming language');
INSERT INTO technology (name, type_id, description) VALUES ('Hadoop', 1, 'Allows for the distributed processing of large data sets across clusters of computers using simple programming models');
INSERT INTO technology (name, type_id, description) VALUES ('iOS SDK', 1, 'Native API for iOS');
INSERT INTO technology (name, type_id, description) VALUES ('JQuery', 1, 'A fast, concise, library that simplifies how to traverse HTML documents, handle events, perform animations, and add AJAX');
INSERT INTO technology (name, type_id, description) VALUES ('JQuery Mobile', 1, 'A unified, HTML5-based user interface system for all popular mobile device platforms, built on the rock-solid jQuery and jQuery UI foundation');
INSERT INTO technology (name, type_id, description) VALUES ('.Net', 1, 'A comprehensive and consistent programming model for building Windows applications');
INSERT INTO technology (name, type_id, description) VALUES ('PhoneGap', 1, 'A free and open source framework that allows you to create mobile apps using standardized web APIs for the platforms you care about');
INSERT INTO technology (name, type_id, description) VALUES ('Pyramid', 1, 'A small, fast, down-to-earth Python web application development framework');
INSERT INTO technology (name, type_id, description) VALUES ('Qt', 1, 'A cross-platform application and UI framework for developers using C++ or QML');
INSERT INTO technology (name, type_id, description) VALUES ('Rhomobile', 1, 'An HTML5 application development platform built to meet the needs of the next generation of business mobility');
INSERT INTO technology (name, type_id, description) VALUES ('Ruby on Rails', 1, 'An open-source web framework that is optimized for programmer happiness and sustainable productivity');
INSERT INTO technology (name, type_id, description) VALUES ('Sencha', 1, 'Provides HTML5-based app development tools and services for building universal apps that run on any device');
INSERT INTO technology (name, type_id, description) VALUES ('Sinatra', 1, 'A DSL for quickly creating web applications in Ruby with minimal effort');
INSERT INTO technology (name, type_id, description) VALUES ('Spring', 1, 'An application development framework for enterprise Java');
INSERT INTO technology (name, type_id, description) VALUES ('Struts', 1, 'A free open-source solution for creating Java web applications');
INSERT INTO technology (name, type_id, description) VALUES ('Symbian SDK', 1, 'Native API for the Symbian OS');
INSERT INTO technology (name, type_id, description) VALUES ('Symfony', 1, 'A PHP framework for web projects');
INSERT INTO technology (name, type_id, description) VALUES ('Titanium', 1, 'Create rich native iOS, Android, hybrid, and mobile web apps from a single JavaScript-based SDK');
INSERT INTO technology (name, type_id, description) VALUES ('Tornado', 1, 'An open source version of the scalable, non-blocking web server and tools that power FriendFeed');
INSERT INTO technology (name, type_id, description) VALUES ('TurboGears', 1, 'A Python web application framework consisting of several WSGI components');
INSERT INTO technology (name, type_id, description) VALUES ('UIQ', 1, 'A software platform based upon Symbian OS that provides additional UI components to the core OS');
INSERT INTO technology (name, type_id, description) VALUES ('Windows Phone SDK', 1, 'Native API for the Windows Phone OS');
INSERT INTO technology (name, type_id, description) VALUES ('Windows SDK', 1, 'Native API for the Windows OS');
INSERT INTO technology (name, type_id, description) VALUES ('web2py', 1, 'Free open source full-stack framework for rapid development of fast, scalable, secure and portable database-driven web-based applications');
INSERT INTO technology (name, type_id, description) VALUES ('Zepto', 1, 'A minimalist Javascript library for modern browsers');


INSERT INTO technology (name, type_id, description) VALUES ('ActionScript', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Ada', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Assembly', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Awk', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Bash', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('C', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('C++', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('C#', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Clojure', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('COBOL', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('CoffeeScript', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('ColdFusion', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('CSS', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('D', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Dart', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Erlang', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('F', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('F#', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Fortran', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Go', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Groovy', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Haskell', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('HTML5', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Java', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Javascript', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('JavaFX Script', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('LaTeX', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Lisp', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Logo', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Lua', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('make', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('MATLAB', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Objective-C', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Object Pascal', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Pascal', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Perl', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('PHP', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Pico', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('PostScript', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Prolog', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Python', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('QtScript', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('R', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Ruby', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Rust', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Scala', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Scheme', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Smalltalk', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('SQL', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Tcl', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('TeX', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('VBScript', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Verilog', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('VHDL', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Visual Basic', 2, '');
INSERT INTO technology (name, type_id, description) VALUES ('Visual Basic .NET', 2, '');


INSERT INTO technology (name, type_id, description) VALUES ('Android OS', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Blackberry OS', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('iOS', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Linux', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Mac OSX', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Symbian', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Unix', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Windows OS', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Windows Mobile', 3, '');
INSERT INTO technology (name, type_id, description) VALUES ('Windows Phone', 3, '');


INSERT INTO technology (name, type_id, description) VALUES ('IDAPro', 4, '');


INSERT INTO technology (name, type_id, description) VALUES ('Cassandra', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('CouchDB', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('MongoDB', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('Mnesia', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('MySQL', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('PostgreSQL', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('Oracle', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('OrientDB', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('Riak', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('SimpleDB', 5, '');
INSERT INTO technology (name, type_id, description) VALUES ('SQLite', 5, '');
