INSERT INTO technology (name, type_id, description) VALUES ('Android SDK', 1, 'Native API for the Android OS');
INSERT INTO technology (name, type_id, description) VALUES ('Angular.js', 1, 'An open source Javascript framework used to augment browser-based applications with MVC');
INSERT INTO technology (name, type_id, description) VALUES ('Backbone.js', 1, 'Gives structure to web applications by providing models, collections, and views over a RESTful JSON interface');
INSERT INTO technology (name, type_id, description) VALUES ('Blackberry SDK', 1, 'Native API for the Blackberry OS');
INSERT INTO technology (name, type_id, description) VALUES ('Cocoa', 1, 'Native object-oriented API for the Mac OS X operating system');
INSERT INTO technology (name, type_id, description) VALUES ('Django', 1, 'A high-level Python Web framework that encourages rapid development and clean, pragmatic design');
INSERT INTO technology (name, type_id, description) VALUES ('Dynamix', 1, 'An open plug-and-play context framework for Android');
INSERT INTO technology (name, type_id, description) VALUES ('Ember.js', 1, 'A framework for creating ambitious web applications');
INSERT INTO technology (name, type_id, description) VALUES ('Flex SDK', 1, 'A powerful, open source application framework that allows you to easily build mobile applications as well as traditional applications for browser and desktop using the same programming model, tool, and codebase');
INSERT INTO technology (name, type_id, description) VALUES ('Grails', 1, 'An open source, full stack, web application framework for the JVM that uses the Groovy programming language');
INSERT INTO technology (name, type_id, description) VALUES ('Hadoop', 1, 'Allows for the distributed processing of large data sets across clusters of computers using simple programming models');
INSERT INTO technology (name, type_id, description) VALUES ('iOS SDK', 1, 'Native API for iOS');
INSERT INTO technology (name, type_id, description) VALUES ('JQuery', 1, 'A fast, concise, library that simplifies how to traverse HTML documents, handle events, perform animations, and add AJAX');
INSERT INTO technology (name, type_id, description) VALUES ('JQuery Mobile', 1, 'A unified, HTML5-based user interface system for all popular mobile device platforms, built on the rock-solid jQuery and jQuery UI foundation');
INSERT INTO technology (name, type_id, description) VALUES ('Knockout', 1, 'Simplify dynamic JavaScript UIs by applying the Model-View-View Model (MVVM) pattern');
INSERT INTO technology (name, type_id, description) VALUES ('Meteor', 1, 'An open source platform for building web apps');
INSERT INTO technology (name, type_id, description) VALUES ('.Net', 1, 'A comprehensive and consistent programming model for building Windows applications');
INSERT INTO technology (name, type_id, description) VALUES ('Node.js', 1, 'A server side software system designed for writing scalable Internet applications in Javascript');
INSERT INTO technology (name, type_id, description) VALUES ('PhoneGap', 1, 'A free and open source framework that allows you to create mobile apps using standardized web APIs for the platforms you care about');
INSERT INTO technology (name, type_id, description) VALUES ('PureMVC', 1, 'A lightweight framework for creating applications based upon the MVC concept');
INSERT INTO technology (name, type_id, description) VALUES ('Pyramid', 1, 'A small, fast, down-to-earth Python web application development framework');
INSERT INTO technology (name, type_id, description) VALUES ('Qt', 1, 'A cross-platform application and UI framework for developers using C++ or QML');
INSERT INTO technology (name, type_id, description) VALUES ('Rhomobile', 1, 'An HTML5 application development platform built to meet the needs of the next generation of business mobility');
INSERT INTO technology (name, type_id, description) VALUES ('Ruby on Rails', 1, 'An open-source web framework that is optimized for programmer happiness and sustainable productivity');
INSERT INTO technology (name, type_id, description) VALUES ('Sencha', 1, 'Provides HTML5-based app development tools and services for building universal apps that run on any device');
INSERT INTO technology (name, type_id, description) VALUES ('Sinatra', 1, 'A DSL for quickly creating web applications in Ruby with minimal effort');
INSERT INTO technology (name, type_id, description) VALUES ('Spine', 1, 'Framework to build Javascript MVC applications');
INSERT INTO technology (name, type_id, description) VALUES ('Spring', 1, 'An application development framework for enterprise Java');
INSERT INTO technology (name, type_id, description) VALUES ('Struts', 1, 'A free open-source solution for creating Java web applications');
INSERT INTO technology (name, type_id, description) VALUES ('Symbian SDK', 1, 'Native API for the Symbian OS');
INSERT INTO technology (name, type_id, description) VALUES ('Symfony', 1, 'A PHP framework for web projects');
INSERT INTO technology (name, type_id, description) VALUES ('Titanium', 1, 'Create rich native iOS, Android, hybrid, and mobile web apps from a single JavaScript-based SDK');
INSERT INTO technology (name, type_id, description) VALUES ('Tornado', 1, 'An open source version of the scalable, non-blocking web server and tools that power FriendFeed');
INSERT INTO technology (name, type_id, description) VALUES ('TurboGears', 1, 'A Python web application framework consisting of several WSGI components');
INSERT INTO technology (name, type_id, description) VALUES ('UIQ', 1, 'A software platform based upon Symbian OS that provides additional UI components to the core OS');
INSERT INTO technology (name, type_id, description) VALUES ('Windows Phone SDK', 1, 'Native API for the Windows Phone OS');
INSERT INTO technology (name, type_id, description) VALUES ('Windows SDK', 1, 'Native API for the Windows OS');
INSERT INTO technology (name, type_id, description) VALUES ('web2py', 1, 'Free open source full-stack framework for rapid development of fast, scalable, secure and portable database-driven web-based applications');
INSERT INTO technology (name, type_id, description) VALUES ('Zepto', 1, 'A minimalist Javascript library for modern browsers');


INSERT INTO technology (name, type_id, description) VALUES ('ActionScript', 2, 'The programming language for the Adobe Flash Player and Adobe AIR runtime environments');
INSERT INTO technology (name, type_id, description) VALUES ('Ada', 2, 'A structured, statically typed, imperative, wide-spectrum, and object-oriented high-level computer programming language, extended from Pascal and other languages');
INSERT INTO technology (name, type_id, description) VALUES ('Assembly', 2, 'A low-level programming language for a computer, microcontroller, or other programmable device, in which each statement corresponds to a single machine code instruction');
INSERT INTO technology (name, type_id, description) VALUES ('Awk', 2, 'An interpreted programming language typically used as a data extraction and reporting tool');
INSERT INTO technology (name, type_id, description) VALUES ('Bash', 2, 'Bash shell scripting');
INSERT INTO technology (name, type_id, description) VALUES ('C', 2, 'A general-purpose programming language initially developed by Dennis Ritchie');
INSERT INTO technology (name, type_id, description) VALUES ('C++', 2, 'C with Classes');
INSERT INTO technology (name, type_id, description) VALUES ('C#', 2, 'A simple, modern, general-purpose, object-oriented programming language developed by Microsoft');
INSERT INTO technology (name, type_id, description) VALUES ('Clojure', 2, 'A dialect of the Lisp programming language created by Rich Hickey');
INSERT INTO technology (name, type_id, description) VALUES ('COBOL', 2, 'COmmon Business-Oriented Language, defining its primary domain in business, finance, and administrative systems for companies and governments');
INSERT INTO technology (name, type_id, description) VALUES ('CoffeeScript', 2, 'A programming language that transcompiles to JavaScript');
INSERT INTO technology (name, type_id, description) VALUES ('Common Lisp', 2, 'A language for software research and advanced development projects that is rich in data types, supported by a high-level language model and garbage collection');
INSERT INTO technology (name, type_id, description) VALUES ('CSS', 2, 'A style sheet language used for describing the look and formatting of a document written in a markup language');
INSERT INTO technology (name, type_id, description) VALUES ('D', 2, 'Attempts to combine the performance of compiled languages with the safety and expressive power of modern dynamic languages');
INSERT INTO technology (name, type_id, description) VALUES ('Dart', 2, 'Goal to replace JavaScript as the working language of web development on the open web platform');
INSERT INTO technology (name, type_id, description) VALUES ('Erlang', 2, 'Designed to support distributed, fault-tolerant, soft-real-time, non-stop applications');
INSERT INTO technology (name, type_id, description) VALUES ('F', 2, 'A subset of Fortan.  A compiled, structured, array programming language especially well suited to education and scientific computing');
INSERT INTO technology (name, type_id, description) VALUES ('F#', 2, 'A succinct, expressive and efficient functional and object-oriented language for .NET');
INSERT INTO technology (name, type_id, description) VALUES ('Fortran', 2, 'A general purpose language that is well suited to numeric computation and scientific computing');
INSERT INTO technology (name, type_id, description) VALUES ('Go', 2, 'An open source programming environment that makes it easy to build simple, reliable, and efficient software');
INSERT INTO technology (name, type_id, description) VALUES ('Groovy', 2, 'An agile and dynamic language for the Java Virtual Machine');
INSERT INTO technology (name, type_id, description) VALUES ('Haskell', 2, 'An advanced purely-functional programming language that allows rapid development of robust, concise, correct software');
INSERT INTO technology (name, type_id, description) VALUES ('HTML5', 2, 'A markup language for structuring and presenting content for the World Wide Web');
INSERT INTO technology (name, type_id, description) VALUES ('Java', 2, 'A general-purpose, concurrent, object-oriented language that is designed to have as few implementation dependencies as possible');
INSERT INTO technology (name, type_id, description) VALUES ('Javascript', 2, 'A scripting language commonly implemented as part of a web browser in order to create enhanced user interfaces and dynamic websites');
INSERT INTO technology (name, type_id, description) VALUES ('Logo', 2, 'A dialect of Lisp, it was designed as a tool for learning');
INSERT INTO technology (name, type_id, description) VALUES ('Lua', 2, 'A powerful, fast, lightweight, embeddable scripting language');
INSERT INTO technology (name, type_id, description) VALUES ('MATLAB', 2, 'A high-level language and interactive environment for numerical computation, visualization, and programming');
INSERT INTO technology (name, type_id, description) VALUES ('Objective-C', 2, 'A superset of the C programming language and provides object-oriented capabilities and a dynamic runtime');
INSERT INTO technology (name, type_id, description) VALUES ('Pascal', 2, 'A small and efficient language intended to encourage good programming practices using structured programming and data structuring');
INSERT INTO technology (name, type_id, description) VALUES ('Perl', 2, 'A general-purpose Unix scripting language');
INSERT INTO technology (name, type_id, description) VALUES ('PHP', 2, 'An HTML-embedded scripting language which allows web developers to write dynamically generated pages quickly');
INSERT INTO technology (name, type_id, description) VALUES ('Pico', 2, 'A tiny but expressive programming language that was designed to teach advance computer science concepts to students in other sciences than computer science');
INSERT INTO technology (name, type_id, description) VALUES ('Prolog', 2, 'A general purpose logic programming language associated with artificial intelligence and computational linguistics');
INSERT INTO technology (name, type_id, description) VALUES ('Python', 2, 'A programming language that lets you work more quickly and integrate your systems more effectively');
INSERT INTO technology (name, type_id, description) VALUES ('QtScript', 2, 'A scripting language that is part of the Qt cross-platform application framework');
INSERT INTO technology (name, type_id, description) VALUES ('R', 2, 'An open source programming language and software environment for statistical computing and graphics');
INSERT INTO technology (name, type_id, description) VALUES ('Ruby', 2, 'A dynamic, interpreted, open source programming language with a focus on simplicity and productivity');
INSERT INTO technology (name, type_id, description) VALUES ('Rust', 2, 'Designed for the creation of large client and server programs that run over the Internet');
INSERT INTO technology (name, type_id, description) VALUES ('Scala', 2, 'A general purpose programming language designed to express common programming patterns in a concise, elegant, and type-safe way');
INSERT INTO technology (name, type_id, description) VALUES ('Scheme', 2, 'A dialect of Lisp, it follows a minimalist design philosophy specifying a small standard core with powerful tools for language extension');
INSERT INTO technology (name, type_id, description) VALUES ('Smalltalk', 2, 'A computer language designed specifically for a wide range of humans rather than a narrow group of computer specialists');
INSERT INTO technology (name, type_id, description) VALUES ('SQL', 2, 'Language designed for managing data in relational database management systems (RDBMS)');
INSERT INTO technology (name, type_id, description) VALUES ('Tcl', 2, 'Scripting language commonly used for rapid prototyping, scripted applications, GUIs and testing');
INSERT INTO technology (name, type_id, description) VALUES ('VBScript', 2, 'Scripting language modeled on Visual Basic');
INSERT INTO technology (name, type_id, description) VALUES ('Verilog', 2, 'A hardware description language used to design and document electronic systems');
INSERT INTO technology (name, type_id, description) VALUES ('VHDL', 2, 'A hardware description language used in electronic design automation to describe digital and mixed-signal systems such as FPGAs and integrated circuits');
INSERT INTO technology (name, type_id, description) VALUES ('Visual Basic', 2, 'Derived from BASIC and enables rapid application development');
INSERT INTO technology (name, type_id, description) VALUES ('Visual Basic .NET', 2, 'The next generation of the Visual Basic language, is a fast and easy way to create .NET-based applications');


INSERT INTO technology (name, type_id, description) VALUES ('Android OS', 3, 'A Linux-based operating system designed primarily for touchscreen mobile devices');
INSERT INTO technology (name, type_id, description) VALUES ('Blackberry OS', 3, 'A mobile OS developed by RIM for its BlackBerry line of smart phone devices');
INSERT INTO technology (name, type_id, description) VALUES ('iOS', 3, 'A mobile OS by Apple');
INSERT INTO technology (name, type_id, description) VALUES ('Linux', 3, 'Unix-like OS built under the model of free and open source software development');
INSERT INTO technology (name, type_id, description) VALUES ('Mac OSX', 3, 'A graphical interface OS by Apple');
INSERT INTO technology (name, type_id, description) VALUES ('Symbian', 3, 'A mobile OS designed for smart phones');
INSERT INTO technology (name, type_id, description) VALUES ('Unix', 3, 'A multitasking, multi-user computer operating system originally developed at Bell Labs');
INSERT INTO technology (name, type_id, description) VALUES ('Windows OS', 3, 'A graphical interface OS by Microsoft');
INSERT INTO technology (name, type_id, description) VALUES ('Windows Phone', 3, 'A mobile OS by Microsoft');


INSERT INTO technology (name, type_id, description) VALUES ('IDAPro', 4, 'A disassembler which generates assembly language source code from machine-executable code');


INSERT INTO technology (name, type_id, description) VALUES ('Cassandra', 5, 'An open source distributed database management system focused toward scalability and high availability');
INSERT INTO technology (name, type_id, description) VALUES ('CouchDB', 5, 'An open source database that focuses on ease of use and embracing the web');
INSERT INTO technology (name, type_id, description) VALUES ('IBM DB2', 5, 'A relational database management system developed by IBM');
INSERT INTO technology (name, type_id, description) VALUES ('Microsoft SQL Server', 5, 'A relational database management system developed by Microsoft');
INSERT INTO technology (name, type_id, description) VALUES ('MongoDB', 5, 'A scalable, high-performance, open source NoSQL database');
INSERT INTO technology (name, type_id, description) VALUES ('Mnesia', 5, 'A distributed, real-time database management system written in the Erlang programming language');
INSERT INTO technology (name, type_id, description) VALUES ('MySQL', 5, 'The popular open source relational database management system');
INSERT INTO technology (name, type_id, description) VALUES ('PostgreSQL', 5, 'A powerful, open source object-relational database system');
INSERT INTO technology (name, type_id, description) VALUES ('Oracle', 5, 'An object-relational database management system produced and marketed by Oracle Corporation');
INSERT INTO technology (name, type_id, description) VALUES ('OrientDB', 5, 'An open source NoSQL database management system written in Java');
INSERT INTO technology (name, type_id, description) VALUES ('Riak', 5, 'The most powerful open-source, distributed database you will ever put into production');
INSERT INTO technology (name, type_id, description) VALUES ('SimpleDB', 5, 'Amazon SimpleDB is a highly available, scalable, and flexible non-relational data store that offloads the work of database administration');
INSERT INTO technology (name, type_id, description) VALUES ('SQLite', 5, 'Cross-platform C library that implements a self-contained, embeddable, zero-configuration SQL database engine');
INSERT INTO technology (name, type_id, description) VALUES ('VoltDB', 5, 'Wicked fast OLTP database');